openapi: 3.0.3
servers:
  - description: Test server
    url: http://10.8.8.219:8018/aс-myid-proxy-v1/
info:
  description: 'API адаптера MyID для ESB'
  version: "0.1.0"
  title: Ac.MyID.Proxy.V1
tags:
  - name: Auth
    description: Данные авторизации
paths:
  /api/v1/authentication/simple-inplace-authentication-request-task:
    post:
      tags:
        - Auth
      summary: 'Запрос на обработку персональных данных'
      operationId: PostSimpleInplaceAuthenticationRequestTask
      description: 'Запрос на обработку персональных данных'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSimpleInplaceAuthenticationRequestTaskRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSimpleInplaceAuthenticationRequestTaskResponse'
        '202':
          description: ACCEPTED
        '400':
          description: BAD_REQUEST
        '403':
          description: FORBIDDEN
        '422':
          description: UNPROCESSABLE_ENTITY
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSimpleInplaceAuthenticationRequestTaskError'
        '500':
          description: INTERNAL_SERVER_ERROR
  /api/v1/authentication/simple-inplace-authentication-request-status:
    post:
      tags:
        - Auth
      summary: 'Результат обработки персональных данных по job_id'
      operationId: PostSimpleInplaceAuthenticationRequestStatus
      description: 'Результат обработки персональных данных по job_id'
      parameters:
        - in: query
          name: job_id
          description: 'Идентификатор обработки запроса'
          schema:
            type: string
            example: 'g055b0e2-a967-5698-b664-77407b3a6eec'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSimpleInplaceAuthenticationRequestStatusResponse'
        '202':
          description: ACCEPTED
        '400':
          description: BAD_REQUEST
        '403':
          description: FORBIDDEN
        '422':
          description: UNPROCESSABLE_ENTITY
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSimpleInplaceAuthenticationRequestStatusError'
        '500':
          description: INTERNAL_SERVER_ERROR
components:
  schemas:
    # /api/v1/authentication/simple-inplace-authentication-request-task
    PostSimpleInplaceAuthenticationRequestTaskRequest:
      type: object
      properties:
        client_id:
          type: string
          description: 'Идентификатор клиента'
        pinfl:
          type: string
          description: 'ПИНФЛ пользователя'
        birth_date:
          type: string
          description: 'Дата рождения'
        photo_from_camera:
          type: object
          description: 'Фотографии лица'
          properties:
            front:
              type: string
              description: 'Фото – лицо смотрит прямо (в формате Data URI)'
        pass_data:
          type: string
          description: 'Серия и номер паспорта'  
        agreed_on_terms:
          type: boolean
          description: 'Согласие физического лица на обработку его персональных данных'
        device:
          type: string
          description: 'Данные об устройстве пользователя'
        threshold:
          type: number
          default: 0.5
          description: 'Значение сравнения фотографий от 0.5 до 1.0'
        external_id:
          type: string
          description: 'Идентификатор запроса клиента'
    PostSimpleInplaceAuthenticationRequestTaskResponse:
      type: object
      properties:
        job_id:
          type: string
          description: 'Идентификатор обработки запроса'
    PostSimpleInplaceAuthenticationRequestTaskError:
      type: object
      description: 'Ошибка: обязательные поля не заполнены'
      properties:
        detail:
          type: array
          description: 'Сведения об ошибке'
          items:
            type: object
            properties:
              loc:
                type: array
                description: 'Локация отсутствующих полей'
                items:
                  type: string
              msg:
                type: string
                description: 'Сообщение'
                default: 'field required'
              type:
                type: string
                description: 'Тип ошибки'
                default: 'value_error.missing'
        body:
          type: object
          description: 'Тело запроса с ошибкой'
    # /api/v1/authentication/simple-inplace-authentication-request-status
    PostSimpleInplaceAuthenticationRequestStatusResponse:
      type: object
      properties:
        response_id:
          type: string
          description: 'Идентификатор ответа'
        result_code:
          type: number
          description: 'Код результата ответа (0 – успешно)'
        result_note:
          type: string
          description: 'Описание результата ответа'
        profile:
          type: object
          description: 'Профиль'
          properties:
            common_data: 
              type: object
              description: 'Общие данные'
              properties:
                first_name:
                  type: string
                  description: 'Имя'
                middle_name:
                  type: string
                  description: 'Отчество'  
                last_name:
                  type: string
                  description: 'Фамилия'
                first_name_en:
                  type: string
                  description: 'Имя на английском языке'  
                last_name_en:
                  type: string
                  description: 'Фамилия на английском языке'  
                pinfl:
                  type: string
                  description: 'Персональный идентификационной номер физического лица'
                inn:
                  type: string
                  description: 'Идентификационной номер налогоплательщика'
                gender:
                  type: string
                  description: 'Пол (1- Мужчина, 2- Женщина)'
                birth_place:
                  type: string
                  description: 'Место рождения'
                birth_country:
                  type: string
                  description: 'Страна рождения'
                birth_country_id:
                  type: string
                  description: 'Идентификатор страны рождения (по справочнику ГЦП)'  
                birth_country_id_cbu:
                  type: string
                  description: 'Идентификатор страны рождения (по справочнику ЦБ)'
                birth_date:
                  type: string
                  description: 'Дата рождения'
                nationality:
                  type: string
                  description: 'Национальность'
                nationality_id:
                  type: string
                  description: 'Идентификатор национальности (по справочнику ГЦП)'  
                nationality_id_cbu:
                  type: string
                  description: 'Идентификатор национальности (по справочнику ЦБ)'  
                citizenship:
                  type: string
                  description: 'Гражданство' 
                citizenship_id:
                  type: string
                  description: 'Идентификатор гражданства (по справочнику ГЦП)'  
                citizenship_id_cbu:
                  type: string
                  description: 'Идентификатор гражданства (по справочнику ЦБ)'
                sdk_hash:
                  type: string
                  description: 'Хэш код, который можно направить в последующих запросах в SDK (вместо реквизитов документа, удостоверяющего личность и даты рождения) в целях получения данных пользователя'
                last_update_pass_data:
                  type: string
                  description: 'Дата и время последнего обновления в системе документа, удостоверяющего личность'
                last_update_inn:
                  type: string
                  description: 'Дата и время последнего обновления в системе идентификационного номера налогоплательщика'
                last_update_address:
                  type: string
                  description: 'Дата и время последнего обновления в системе адреса регистрации'  
            doc_data:
              type: object
              description: 'Документ, удостоверяющий личность'
              properties:
                pass_data:
                  type: string
                  description: 'Серия и номер'
                issued_by:
                  type: string
                  description: 'Место выдачи'
                issued_by_id:
                  type: string
                  description: 'Идентификатор места выдачи'  
                issued_date:
                  type: string
                  description: 'Дата выдачи'
                expiry_date:
                  type: string
                  description: 'Срок действия' 
                doc_type:
                  type: string
                  description: 'Тип документа'
                doc_type_id:
                  type: string
                  description: 'Идентификатор типа документа'  
                doc_type_id_cbu:
                  type: string
                  description: 'Идентификатор типа документа (по справочник ЦБ)'
            contacts:
              type: object
              description: 'Контакты'
              properties:
                phone:
                  type: string
                  description: 'Номер телефона'
                email:
                  type: string
                  description: 'Адрес электронной почты'
            address:
              type: object
              description: 'Адрес'
              properties:  
                permanent_address:
                  type: string
                  description: 'Адрес постоянной регистрации'
                temporary_address:
                  type: string
                  description: 'Адрес временной регистрации'
                permanent_registration:
                  type: object
                  description: 'Прописка'
                  properties:
                    region:
                      type: string
                      description: 'Значение региона'  
                    address:
                      type: string
                      description: 'Адрес'
                    country:
                      type: string
                      description: 'Значение страны'
                    cadastre:
                      type: string
                      description: 'Кадастровый номер'
                    district:
                      type: string
                      description: 'Значение района (города)' 
                    region_id:
                      type: string
                      description: 'Идентификационной номер региона (по справочнику МВД)'
                    country_id:
                      type: string
                      description: 'Идентификационный номер страны (По справочнику МВД)'
                    district_id:
                      type: string
                      description: 'Идентификационный номер района/города (По справочнику МВД)'
                    region_id_cbu:
                      type: string
                      description: 'Идентификационной номер региона (по справочнику ЦБ)'  
                    country_id_cbu:
                      type: string
                      description: 'Идентификационный номер страны (По справочнику ЦБ)'
                    district_id_cbu:
                      type: string
                      description: 'Идентификационный номер района/города (По справочнику ЦБ)'
                    registration_date:
                      type: string
                      description: 'Дата регистрации'
                temporary_registration:
                  type: object
                  description: 'Прописка'
                  properties:
                    region:
                      type: string
                      description: 'Значение региона'  
                    address:
                      type: string
                      description: 'Адрес'
                    country:
                      type: string
                      description: 'Значение страны'
                    cadastre:
                      type: string
                      description: 'Кадастровый номер'
                    district:
                      type: string
                      description: 'Значение района (города)' 
                    date_from:
                      type: string
                      description: 'Дата начала регистрации'
                    date_till:
                      type: string
                      description: 'Дата окончания регистрации' 
                    region_id:
                      type: string
                      description: 'Идентификационной номер региона (по справочнику МВД)'
                    country_id:
                      type: string
                      description: 'Идентификационный номер страны (По справочнику МВД)'
                    district_id:
                      type: string
                      description: 'Идентификационный номер района/города (По справочнику МВД)'
                    region_id_cbu:
                      type: string
                      description: 'Идентификационной номер региона (по справочнику ЦБ)'  
                    country_id_cbu:
                      type: string
                      description: 'Идентификационный номер страны (По справочнику ЦБ)'
                    district_id_cbu:
                      type: string
                      description: 'Идентификационный номер района/города (По справочнику ЦБ)'
            authentication_method:
              type: string
              description: 'Метод аутентификации (simple, strong)'
        comparison_value:
          type: number
          description: 'Результат сравнения (0.5-1.0 успешно)'
    PostSimpleInplaceAuthenticationRequestStatusError:
      type: object
      description: 'Ошибка: обязательные поля не заполнены'
      properties:
        detail:
          type: array
          description: 'Сведения об ошибке'
          items:
            type: object
            properties:
              loc:
                type: array
                description: 'Локация отсутствующих полей'
                items:
                  type: string
              msg:
                type: string
                description: 'Сообщение'
                default: 'field required'
              type:
                type: string
                description: 'Тип ошибки'
                default: 'value_error.missing'
        body:
          type: object
          description: 'Тело запроса с ошибкой'